import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Import coingecko-api
const CoinGecko = require('coingecko-api');
 
// Initiate the CoinGecko API Client
const CoinGeckoClient = new CoinGecko();


export async function getStaticProps() {
  const btc = await CoinGeckoClient.coins.fetch('bitcoin', {tickers: false, developer_data: false}); 

  return {
    props: { btc }
  }
}


export default function Home({ btc }) {
  const { data } = btc;
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>LUAN Portfolio Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

      </main>

      <footer>

      </footer>
    </div>
  )
}
