import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Import coingecko-api
const CoinGecko = require('coingecko-api');
 
// Initiate the CoinGecko API Client
const CoinGeckoClient = new CoinGecko();


export async function getStaticProps() {
  const btc = await CoinGeckoClient.coins.fetch('bitcoin', {tickers: false, developer_data: false});
  
  const luanPM = await fetch('https://api.npoint.io/3a71cd029b83a17ded81/Portfolio');
  const portfolio = await luanPM.json();

  return {
    props: { btc, portfolio }
  }
}


export default function Home({ btc, portfolio }) {
  const { data } = btc;
  // console.log(data);
  // console.log(portfolio);

  return (
    <div className="container">
      <Head>
        <title>LUAN Portfolio Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
